from __future__ import annotations
from typing import Any, AsyncIterator, Dict, List, Optional, Protocol

class Storage(Protocol):
    async def create_or_load_run(self, task_id: str, tenant_id: str) -> Dict[str, Any]: ...
    async def set_run_state(self, run_id: str, state: str) -> None: ...
    async def persist_update(self, run_id: str, update: Dict[str, Any]) -> None: ...
    async def load_tenant_context(self, tenant_id: str) -> Dict[str, Any]: ...
    async def create_approval_request(self, run_id: str, payload: Dict[str, Any]) -> str: ...
    async def wait_for_approval(self, approval_id: str) -> Dict[str, Any]: ...
    async def get_step_result(self, idem_key: str) -> Optional[Dict[str, Any]]: ...
    async def save_step_result(self, idem_key: str, step_result: Dict[str, Any]) -> None: ...
